import type { Metadata } from 'next'
import { Fira_Code} from 'next/font/google'
import "./styles/index.scss";
import Navbar from '@/components/navbar/Navbar';

const firaCode = Fira_Code({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${firaCode.className} layout`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
